export const BASE_URL = 'https://pokeapi.co/api/v2/';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR';
export const GET_POKEMON_DETAIL_SUCCESS = 'GET_POKEMON_DETAIL_SUCCESS';
export const GET_POKEMON_DETAIL_ERROR = 'GET_POKEMON_DETAIL_ERROR';
